# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('fallballapp', '0001_initial'), ('fallballapp', '0002_auto_20160513_1601')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('usage', models.IntegerField(blank=True)),
                ('admin', models.BooleanField(default=False)),
                ('limit', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallballapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallballapp.Reseller'),
        ),
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
