# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
